name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: Can be used to set a specific version. Use 'auto' for automatic version calculation
        type: string

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@aa83050fcb03fe69f7bff031a5452f387d19aa23 # 2.0.20
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
