name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: Can be used to set a specific version. Use 'auto' for automatic version calculation
        type: string

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@c6718b5723b2e69baff45a33d27313f326954b3a # 2.0.39
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
