name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: Can be used to set a specific version. Use 'auto' for automatic version calculation
        type: string

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@43a933c8b6cf02c324997261163fd029dbf5cd6c # 2.0.14
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
